#!/usr/bin/env python3
"""Push Sirat Al Huda to GitHub safely.
Idempotent — safe to re-run.
  - git init if needed
  - writes a proper .gitignore (Capacitor/iOS/Vite/Node)
  - scans for secrets before staging (.env, .p8, JWTs in src/)
  - commits
  - pushes via gh CLI if available, otherwise prints manual steps
"""
import subprocess, pathlib, sys, shutil, os

REPO_DIR    = pathlib.Path.home() / "Downloads/sirat-capacitor-3"
REPO_NAME   = "sirat-al-huda"            # tweak if you want a different name
VISIBILITY  = "--private"                # change to "--public" if desired
DESCRIPTION = "Sirat Al Huda — Muslim daily practice companion (Capacitor + React + Supabase)"

GITIGNORE = """# === Node ===
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# === Vite build output ===
dist/
*.local

# === macOS ===
.DS_Store

# === Editor / IDE ===
.vscode/
.idea/
*.swp

# === Environment / secrets ===
.env
.env.*
!.env.example
*.p8
*.p12
GoogleService-Info.plist

# === iOS / Xcode ===
ios/App/build/
ios/App/Pods/
ios/DerivedData/
ios/App/App.xcworkspace/xcuserdata/
ios/App/App.xcodeproj/xcuserdata/
ios/App/App.xcodeproj/project.xcworkspace/xcuserdata/
xcuserdata/
*.xcuserstate

# Capacitor copies the web build here — regenerated by `npx cap sync`
ios/App/App/public/

# Cordova plugins copied by Capacitor
ios/capacitor-cordova-ios-plugins/

# === Patcher backups ===
*.bak
.push-setup-backups/

# === Supabase local ===
supabase/.temp/
supabase/.branches/

# === Misc ===
*.log
"""

def run(cmd, check=False):
    r = subprocess.run(cmd, cwd=REPO_DIR, capture_output=True, text=True)
    if check and r.returncode != 0:
        print(f"✗ Command failed: {' '.join(cmd)}\n{r.stderr}")
        sys.exit(1)
    return r.returncode, r.stdout.strip(), r.stderr.strip()

# ─── 0. Sanity ────────────────────────────────────────────────────────────
if not REPO_DIR.exists():
    print(f"✗ {REPO_DIR} doesn't exist")
    sys.exit(1)
os.chdir(REPO_DIR)
print(f"→ Working in {REPO_DIR}\n")

# ─── 1. Git init ──────────────────────────────────────────────────────────
if not (REPO_DIR / ".git").exists():
    print("→ Initializing git repo (main branch)")
    run(["git", "init", "-b", "main"], check=True)
else:
    print("✓ Git repo already initialized")

# ─── 2. .gitignore ────────────────────────────────────────────────────────
gi = REPO_DIR / ".gitignore"
if not gi.exists() or "ios/App/App/public/" not in gi.read_text():
    gi.write_text(GITIGNORE)
    print("✓ .gitignore written")
else:
    print("✓ .gitignore already configured")

# ─── 3. Secret scan ───────────────────────────────────────────────────────
print("\n→ Scanning for potential secrets...")
issues = []

# .env / .p8 files (these are gitignored, but flag presence)
for p in REPO_DIR.rglob(".env*"):
    if "node_modules" not in str(p) and "ios/App/Pods" not in str(p):
        issues.append(f"  ⚠ Env file: {p.relative_to(REPO_DIR)} (gitignored, won't be pushed)")
for p in REPO_DIR.rglob("*.p8"):
    if "node_modules" not in str(p):
        issues.append(f"  ⚠ APNs key: {p.relative_to(REPO_DIR)} (gitignored, won't be pushed)")

# JWT-like strings in source paths that WILL be committed
scan_paths = [p for p in ["src", "supabase"] if (REPO_DIR / p).exists()]
if scan_paths:
    rc, out, _ = run(["grep", "-rIlE", r"eyJ[A-Za-z0-9_-]{30,}"] + scan_paths)
    if out:
        for line in out.splitlines():
            issues.append(f"  🚨 JWT-like string in: {line} (WILL be committed — review!)")

if issues:
    for i in issues:
        print(i)
    print("\n  Hit Ctrl+C now to investigate, or press Enter to continue.")
    try:
        input()
    except (EOFError, KeyboardInterrupt):
        print("\nAborted.")
        sys.exit(0)
else:
    print("  ✓ No obvious secrets found")

# ─── 4. Stage + commit ────────────────────────────────────────────────────
print("\n→ Staging files...")
run(["git", "add", "-A"], check=True)
rc, status_out, _ = run(["git", "status", "--short"])

if not status_out:
    print("  ✓ Nothing new to commit")
else:
    print(f"  {len(status_out.splitlines())} files staged")

    # First commit? Check for any existing HEAD
    rc_head, _, _ = run(["git", "rev-parse", "HEAD"])
    msg = "Initial commit: Sirat Al Huda (pre-launch)" if rc_head != 0 else "Update: latest pre-launch work"

    print(f"→ Committing: \"{msg}\"")
    # Set committer identity if missing (avoids "Please tell me who you are" error)
    rc, name, _ = run(["git", "config", "user.name"])
    if not name:
        run(["git", "config", "user.name", "Hassan Tageddine"])
        run(["git", "config", "user.email", "hassantageddine@users.noreply.github.com"])
        print("  (set local git user — change with `git config user.email <real-email>`)")

    rc, out, err = run(["git", "commit", "-m", msg])
    if rc == 0:
        print(f"  ✓ committed")
    else:
        print(f"  ⚠ commit issue: {err or out}")

# ─── 5. Remote ────────────────────────────────────────────────────────────
print("\n→ Checking remote...")
rc, remote_url, _ = run(["git", "remote", "get-url", "origin"])
if rc == 0 and remote_url:
    print(f"  ✓ Remote origin: {remote_url}")
    print("\n→ Pushing to existing remote...")
    rc, out, err = run(["git", "push", "-u", "origin", "main"])
    print(out or err)
    print("\n✓ Done." if rc == 0 else "\n⚠ Push failed — see above.")
    sys.exit(0 if rc == 0 else 1)

print("  (no remote configured)")

# ─── 6. gh CLI path ───────────────────────────────────────────────────────
if shutil.which("gh"):
    rc, _, _ = run(["gh", "auth", "status"])
    if rc == 0:
        print(f"\n→ Creating {VISIBILITY[2:]} GitHub repo '{REPO_NAME}' via gh CLI...")
        rc, out, err = run([
            "gh", "repo", "create", REPO_NAME,
            VISIBILITY,
            "--source=.",
            "--remote=origin",
            "--push",
            "--description", DESCRIPTION,
        ])
        print(out or err)
        if rc == 0:
            print("\n✓ Repo created and pushed.")
        else:
            print(f"\n⚠ gh repo create failed.")
        sys.exit(0 if rc == 0 else 1)
    else:
        print("\n  gh CLI found but not authenticated. Run:")
        print("    gh auth login")
        print("  Then re-run this script.")
        sys.exit(0)

# ─── 7. Manual fallback ───────────────────────────────────────────────────
print("\n→ gh CLI not installed. Two options:\n")
print("  Option A — Install gh CLI (one-time setup):")
print("    brew install gh")
print("    gh auth login")
print("    python3 ~/Downloads/push_to_github.py        # re-run this script\n")
print("  Option B — Create the repo manually:")
print("    1. Go to https://github.com/new")
print(f"    2. Name: {REPO_NAME}    Visibility: Private")
print("    3. DO NOT add README, .gitignore, or license (we already have these)")
print("    4. Then run:")
print(f"       cd {REPO_DIR}")
print(f"       git remote add origin https://github.com/<your-username>/{REPO_NAME}.git")
print( "       git push -u origin main")
